# bashrc

#      the shell we usually get is bash. since we want to be able to move around in bash we start by configuring the bash environment for this user
#      we are letting freshrc compile a single file for us


# Use the system config if it exists
if [ -f /etc/bashrc ]; then
    . /etc/bashrc        # --> Read /etc/bashrc, if present.
elif [ -f /etc/bash.bashrc ]; then
    . /etc/bash.bashrc   # --> Read /etc/bash.bashrc, if present.
fi

[[ -f ~/.bashrc_settings ]] && source ~/.bashrc_settings && echo "loaded bash settings"



# The following lines are only for interactive shells
[[ $- = *i* ]] || return

# shared shell
source ~/.fresh/build/shell.sh && echo "loaded common shell"

# bash customizations and extensions
[[ -f ~/.bashrc_plugins ]] && source ~/.bashrc_plugins && echo "loaded bash plugins"
