#
# Executes commands at login post-zshrc.
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  fortune -a
  print
fi

# inform about which shell we are using
ps $$

## System ruby path set early for tmuxinator
export PATH="$PATH:/root/.gem/ruby/2.4.0/bin"
## rvm http://stackoverflow.com/a/27204087
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
## Ruby
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting


# list tmux projects
if (( $+commands[tmuxinator] )); then
  tmuxinator list

fi
