#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi


#
# Editors

export VISUAL='emacs'
export PAGER='less'
export ALTERNATE_EDITOR='emacs'
export EDITOR='emacsclient'
export VISUAL='emacsclient'
export USE_EDITOR="$EDITOR"
#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
 cdpath=(
   $cdpath
 )

# Set the list of directories that Zsh searches for programs.
path=(
  ${ZDOTDIR:-$HOME}/{bin,sbin}
  ${ZDOTDIR:-$HOME}/.config/composer/vendor/bin
  ${ZDOTDIR:-$HOME}/scripts
  $path
  /usr/local/{bin,sbin}
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="$(mktemp -d)"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
