#
# Defines environment variables.
#



#
# Some handy directories
#
export USR_DIR=$HOME
export PROJECTS_DIR=$HOME/dev
export DOTFILES_DIR=$USR_DIR/.dotfiles
export BRAINDUMP_DIR=$USR_DIR/braindump
export FRESH_DIR=$USR_DIR/.fresh
export ZSH_DIR=$FRESH_DIR/build/zsh


# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set the list of directories that Zsh searches for programs.
path=(

#${ZDOTDIR:-$HOME}/{bin,sbin}
#${ZDOTDIR:-$HOME}/.fresh/source/rosenstrauch/git-achievements
${ZDOTDIR:-$HOME}/.composer/vendor/bin
$path
/usr/local/{bin,sbin}
)
