#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set the list of directories that Zsh searches for programs.
path=(
/usr/local/{bin,sbin}
${ZDOTDIR:-$HOME}/{bin,sbin}
${ZDOTDIR:-$HOME}/.fresh/source/rosenstrauch/git-achievements
$path
)
